# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
       - setup_remote_docker:
            version: 17.09.0-ce
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
