# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    docker:
      - image: golang:1.9.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Login to registry
          command: |
             docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - run:
          name: Tag container
          command: |
             docker tag app quay.io/mafonso/specimen:$CIRCLE_BUILD_NUM
      - run:
          name: Push container
          command: |
             docker push quay.io/mafonso/specimen:$CIRCLE_BUILD_NUM
  test:
    docker:
        - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker:
          version: 17.09.0-ce
     - run:
          name: run container
          command: |
             docker run quay.io/mafonso/specimen:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
      - test:
          requires:
            - build
