# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    docker:
      - image: golang:1.9.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Login to registry
          command: |
             docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - run:
          name: Push container
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag app quay.io/mafonso/specimen:${CIRCLE_SHA1}
              docker push quay.io/mafonso/specimen:${CIRCLE_SHA1}
            fi
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar


  test:
    docker:
        - image: docker:17.09.0-ce-git
    steps:
      - setup_remote_docker:
          version: 17.09.0-ce
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: run container
          command: |
              docker run -d -p8080:8080 quay.io/mafonso/specimen:${CIRCLE_SHA1}
      - run:
          name: Call service
          command: |
              curl localhost:8080/status

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
      - test:
          requires:
            - build
